/**
 * Synthetic workload generator shared by the cache bench and long-context
 * invariant tests.
 *
 * Produces a deterministic sequence of User/Claude turns with optional
 * tool_use → tool_result pairs. Tokens are generated by a seeded RNG so
 * a given config always yields the same workload — strategies are
 * compared on identical inputs.
 *
 * Imports `ContentBlock` from the local context-manager package via the
 * re-export through membrane.
 */

import type { ContentBlock } from '@animalabs/membrane';

export interface WorkloadConfig {
  /** Number of conversation turns (each turn is one message). */
  turns: number;
  avgUserTokens: number;
  avgAssistantTokens: number;
  /** Probability that an assistant turn includes a tool_use block (followed
   *  by a forced tool_result on the next turn, which counts as a separate
   *  turn). */
  toolCallProbability: number;
  seed: number;
}

export interface WorkloadTurn {
  participant: 'User' | 'Claude';
  content: ContentBlock[];
}

class RNG {
  private state: number;
  constructor(seed: number) {
    this.state = (seed | 0) || 1;
  }
  next(): number {
    this.state = (Math.imul(this.state, 1103515245) + 12345) | 0;
    const u = (this.state >>> 0) & 0x7fffffff;
    return u / 0x7fffffff;
  }
  jitter(target: number, frac = 0.4): number {
    const delta = (this.next() - 0.5) * 2 * frac * target;
    return Math.max(20, Math.round(target + delta));
  }
}

const WORDS = [
  'the', 'quick', 'brown', 'fox', 'jumps', 'over', 'lazy', 'dog',
  'agent', 'context', 'cache', 'prefix', 'token', 'compress', 'memory',
  'chunk', 'summary', 'message', 'query', 'response', 'result', 'tool',
  'foo', 'bar', 'baz', 'qux', 'alpha', 'beta', 'gamma', 'delta',
];

function lorem(rng: RNG, tokens: number): string {
  const targetChars = tokens * 4;
  const parts: string[] = [];
  let len = 0;
  while (len < targetChars) {
    const w = WORDS[Math.floor(rng.next() * WORDS.length)];
    parts.push(w);
    len += w.length + 1;
  }
  return parts.join(' ').slice(0, targetChars);
}

export function generateWorkload(cfg: WorkloadConfig): WorkloadTurn[] {
  const rng = new RNG(cfg.seed);
  const turns: WorkloadTurn[] = [];
  let toolCounter = 0;
  let pendingToolUseId: string | null = null;
  let lastSpeaker: 'User' | 'Claude' = 'Claude';

  for (let i = 0; i < cfg.turns; i++) {
    // Pending tool_result must come from User (matches Anthropic role mapping
    // since tool_result blocks go on user-role messages).
    if (pendingToolUseId) {
      const resultTokens = rng.jitter(80, 0.6);
      turns.push({
        participant: 'User',
        content: [
          {
            type: 'tool_result',
            toolUseId: pendingToolUseId,
            content: [{ type: 'text', text: lorem(rng, resultTokens) }],
          } as ContentBlock,
        ],
      });
      pendingToolUseId = null;
      lastSpeaker = 'User';
      continue;
    }

    // Alternate, but the speaker after a tool_result is always Claude.
    const nextSpeaker: 'User' | 'Claude' =
      lastSpeaker === 'User' ? 'Claude' : 'User';

    if (nextSpeaker === 'User') {
      const tokens = rng.jitter(cfg.avgUserTokens);
      turns.push({
        participant: 'User',
        content: [{ type: 'text', text: lorem(rng, tokens) }],
      });
    } else {
      const tokens = rng.jitter(cfg.avgAssistantTokens);
      const callTool = rng.next() < cfg.toolCallProbability;
      if (callTool) {
        const id = `toolu_${toolCounter++}`;
        pendingToolUseId = id;
        turns.push({
          participant: 'Claude',
          content: [
            { type: 'text', text: lorem(rng, Math.floor(tokens * 0.6)) },
            {
              type: 'tool_use',
              id,
              name: 'fake_tool',
              input: { q: `arg-${i}`, i },
            } as ContentBlock,
          ],
        });
      } else {
        turns.push({
          participant: 'Claude',
          content: [{ type: 'text', text: lorem(rng, tokens) }],
        });
      }
    }
    lastSpeaker = nextSpeaker;
  }

  return turns;
}
